### ISSUE TITLE
Api schema?

### ISSUE THREAD

**Issue by lluiscab** [mitchfizz05/Sphinx#1]
I have seen this project and It looks great but It seems abandoned. I'm on the progress on making my own platform for personal use and I've found this.

Do you guys have any api schema / self made docs that could help me?

**Comment by mitchfizz05** [comment]
We never actually documented how the API worked, I was planning on it but never got around to it.

Some of the basic stuff is documented on [wiki.vg](http://wiki.vg/Realms_API), but it is quite out of date and still uses usernames rather than UUIDs.

The Realms library contains a lot of very useful information and is relatively easy to understand, so I'd suggest decompiling that.
